name: Update GitHub Analytics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Analytics
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: Kyren-in
          template: terminal

          base: header, activity, metadata

          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used

          config_timezone: Asia/Kolkata

          filename: profile/metrics.svg

          output_action: commit
          committer_branch: main
